### ISSUE TITLE
Adadmin doesn't correctly detect https (vs http)

### ISSUE THREAD

**Issue by durkinio** [giuliopons/adadmin#102]
I've installed an instance of Adadmin, and CNAME'd multiple subdomains to it.

It works fine in that I can login without issue and embed the code, but the position code generated contains http, not https. Image requests also seem to be routed through http, not https (even though I updated the position code to https).

I've put cloudflare in front of it for the moment, but i'm still getting 'Does not use https' errors from pagespeed related to this. 

Is this a known issue?

**Comment by giuliopons** [comment]
Hi,
can you give me an access to try to investigate the issue? The problem never happened in my installations and also from other users. Send me privately a login/ftp access to giulio@barattalo.it, I will take a look on it
Giulio

**Comment by durkinio** [comment]
Apologies... turns out it was a Cloudflare issue. Sorted now so closing. Thanks for the super fast response!
