### ISSUE TITLE
HTML5 banners Responsive errors

### ISSUE THREAD

**Issue by povpie** [giuliopons/adadmin#56]
Hi pons, here are 2 bugs I found for displaying html5 banners: on codepen [(link)](https://codepen.io/celioss/pen/zYabEjq) example I'm using an html5 banner(yellow taxi) with size 973x250 with responsive checked on AdAdmin.

**Issue 1**: the <body of banner doesn't resize the height attribute (the 250px is fixed). As you can see, there's an "invisible" element (body) that pushes everything down (blue div) if the banner width is smaller than 973px. 

![Screenshot (46)](https://user-images.githubusercontent.com/91896759/206481469-6f1fa73e-b042-481b-9c48-9a13d25dadca.png)

**Issue 2**: the banner isn't responsive for width larger than banner width (973px), if the container is larger: the banner has a hard limit at 973px;

![Screenshot (47)](https://user-images.githubusercontent.com/91896759/206483134-e6e4b601-5a4a-4e7b-855d-f2ba83d2a4a6.png)

**Comment by giuliopons** [comment]
I've seen that there is a bug when the iframe containing the banner shows content from another domain. This is what is happening on codepen since the banner is n barattalo and the html showing it is on codepen servers.
I'm studying a workaround to pass the size of the banner from within the iframe... I'll let you know.

From the blue box position I don't know at this moment and I'm waiting your adv since with my test it doesn't happen.

**Comment by giuliopons** [comment]
The actual code that resize the height of the `iframe` works only if the banner is showed on the same domain of the site that hosts AdAdmin.

I've made a fix that fix this behaviour also crossbrowser, but it needs a small function inside the code of your HTML5 banner.
Here it is:

`<script>

	/*
		add this script in <head> to update the height of the banner
	*/
	function adjust_iframe_height(){
		if(typeof(window.resdefined)=="undefined"){
			window.resdefined = true;
			window.onresize = adjust_iframe_height;
		}
		var actual_height = document.body.scrollHeight;
		parent.postMessage(actual_height,"*");
	}
	window.addEventListener("load", (event) => { adjust_iframe_height() });

</script>
`

This script uses `postMessage` to tell to the parent the `height` of the `iframe`. On the parent AdAdmin has a new function that handle this call and resize the iframe.

I will update AdAdmin to use this new code.

**Comment by giuliopons** [comment]
Will be updated in 3.996

**Comment by povpie** [comment]
Hi pons, sorry for the late reply.

Banner is here: https://we.tl/t-CQttO0dlaJ

So, for all html5 banners I'd need to insert that <script if I use adAdmin
or will the update fix the issue generally?
I'll check on demo if it works.

Best.

**Comment by giuliopons** [comment]
To fix the issue an update of AdAdmin is needed because a script is necessary both on the `ser.php`  that show the banner, and another script (the one posted in my previous comment) in your banner. Because of cross domain issues.

**Comment by giuliopons** [comment]
Which is the tool that you have used to create the banner?

**Comment by giuliopons** [comment]
Your banner scale the size of himself in a different way of mine, so for your ad 973x250 you have to add this code in your banner (you can open the index.html file and go to the end of head tag and add this function):

```
<script>
	function adjust_iframe_height(){
		if(typeof(window.resdefined)=="undefined"){
			window.resdefined = true;
			window.onresize = adjust_iframe_height;
		}
		var actual_height = document.body.scrollWidth * 250/973;
		parent.postMessage(actual_height,"*");
	}
	window.addEventListener("load", (event) => { adjust_iframe_height() });
</script>

```

This function will recalculate the height and communicate to AdAdmin script to resize the iframe properly.

You also need to copy the clicktag from the AdAdmin banner page and place it here in your banner to make it work, you have to edit your index.html file also here:

![image](https://user-images.githubusercontent.com/1871627/206932343-79392cb6-ee16-492d-a946-457bddef4ad7.png)

I'm going to upload the fix to Codecanyon to make it work.

**Comment by giuliopons** [comment]
I've just uploaded the fix v.3995b

**Comment by povpie** [comment]
> Which is the tool that you have used to create the banner?

I don't remember exactly where this one was made, I use onlymega, creatopy and bannerboo. If I'm not mistaken, this one was made on creatopy but I might be wrong. As soon as I have a free time I'll test it out on demo again. Thanks again Pons.
